// <auto-generated />
using System;
using BibliotecaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaApp.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260309025843_SeedDataInicial")]
    partial class SeedDataInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaApp.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            FechaNacimiento = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Británica",
                            Nombre = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 102,
                            FechaNacimiento = new DateTime(1927, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Colombiana",
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = 103,
                            FechaNacimiento = new DateTime(1892, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Británica",
                            Nombre = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 104,
                            FechaNacimiento = new DateTime(1903, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Británica",
                            Nombre = "George Orwell"
                        },
                        new
                        {
                            Id = 105,
                            FechaNacimiento = new DateTime(1942, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Chilena",
                            Nombre = "Isabel Allende"
                        });
                });

            modelBuilder.Entity("BibliotecaApp.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("BibliotecaApp.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AnioPublicacion = 1997,
                            AutorId = 101,
                            Disponible = true,
                            ISBN = "978-8478884452",
                            Titulo = "Harry Potter y la Piedra Filosofal"
                        },
                        new
                        {
                            Id = 102,
                            AnioPublicacion = 1998,
                            AutorId = 101,
                            Disponible = true,
                            ISBN = "978-8478884469",
                            Titulo = "Harry Potter y la Cámara Secreta"
                        },
                        new
                        {
                            Id = 103,
                            AnioPublicacion = 1967,
                            AutorId = 102,
                            Disponible = true,
                            ISBN = "978-0060883287",
                            Titulo = "Cien Años de Soledad"
                        },
                        new
                        {
                            Id = 104,
                            AnioPublicacion = 1985,
                            AutorId = 102,
                            Disponible = true,
                            ISBN = "978-0307389732",
                            Titulo = "El Amor en los Tiempos del Cólera"
                        },
                        new
                        {
                            Id = 105,
                            AnioPublicacion = 1954,
                            AutorId = 103,
                            Disponible = true,
                            ISBN = "978-8445073704",
                            Titulo = "El Señor de los Anillos: La Comunidad del Anillo"
                        },
                        new
                        {
                            Id = 106,
                            AnioPublicacion = 1937,
                            AutorId = 103,
                            Disponible = true,
                            ISBN = "978-8445073858",
                            Titulo = "El Hobbit"
                        },
                        new
                        {
                            Id = 107,
                            AnioPublicacion = 1949,
                            AutorId = 104,
                            Disponible = true,
                            ISBN = "978-0451524935",
                            Titulo = "1984"
                        },
                        new
                        {
                            Id = 108,
                            AnioPublicacion = 1945,
                            AutorId = 104,
                            Disponible = true,
                            ISBN = "978-0451526342",
                            Titulo = "Rebelión en la Granja"
                        },
                        new
                        {
                            Id = 109,
                            AnioPublicacion = 1982,
                            AutorId = 105,
                            Disponible = true,
                            ISBN = "978-8401352508",
                            Titulo = "La Casa de los Espíritus"
                        },
                        new
                        {
                            Id = 110,
                            AnioPublicacion = 1987,
                            AutorId = 105,
                            Disponible = true,
                            ISBN = "978-8401352966",
                            Titulo = "Eva Luna"
                        });
                });

            modelBuilder.Entity("BibliotecaApp.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("LibroId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("BibliotecaApp.Models.Libro", b =>
                {
                    b.HasOne("BibliotecaApp.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("BibliotecaApp.Models.Prestamo", b =>
                {
                    b.HasOne("BibliotecaApp.Models.Estudiante", "Estudiante")
                        .WithMany("Prestamos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaApp.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("BibliotecaApp.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaApp.Models.Estudiante", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BibliotecaApp.Models.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
